### PR TITLE
Clang material Index type fix

### PR DESCRIPTION
**Pull request by ghost**
Compiling with Clang gives the following error:

```
./three/renderers/impl/gl_renderer.ipp:792:33: fatal error: ambiguous
      conversion for static_cast from 'Index' (aka 'IndexT<int, -1>') to 'size_t' (aka 'unsigned long')
    return geometry->materials[ static_cast<size_t>(geometryGroup->materialIndex) ].get();

./three/utils/index.hpp:21:3: note: candidate function
  operator T() const { return value; }

./three/utils/index.hpp:22:3: note: candidate function
  operator uint32_t() const { return static_cast<uint32_t>(value); }

./three/utils/index.hpp:23:3: note: candidate function
  operator uint64_t() const { return static_cast<uint64_t>(value); }
```

This is fixed by adding a size_t operator to the IndexT.

### CODE REVIEW

**Comment by jdduke** [comment]
Unfortunately this change breaks other compilers.  Does it compile OK for you if you simply remove the explicit static_cast<size_t> from gl_renderer.ipp:792? That appears to work for me locally both with GCC and MSVC.

**Comment by ghost** [comment]
Still gives an ambiguous error, unfortunately.

**Comment by jdduke** [comment]
Dang, what if we simply use the value without the implicit cast (as we've already checked it for validity)? Something like:

return geometry->materials[ geometryGroup->materialIndex.value ].get();

Does that work for you?

**Comment by ghost** [comment]
I guess that might work.

I've bootstrapped the project on my PC. Adding size_t gives an error at compile time that uint32_t is already defined, so it seems to interpret size_t as uint32_t. 

What about removing uint32_t and uint64_t and leaving size_t in place? Given the use of IndexT size_t might suffice? ~~Just using size_t compiles on both my setups.~~ Correction: only works on my PC :-)

**Comment by ghost** [comment]
Accessing .value does seem to work and would require two lines of code changed. Not sure if there are any other implications.

**Comment by jdduke** [comment]
Looks good, thank you!  I think all hopes of something resembling type safety were thrown out the window when I based the code on a Javascript project :)

**Pull request merged**
